spring.application.name=API-GATEWAY
server.port=8080

eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=order
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/orders/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/order-realm/protocol/openid-connect/certs
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://172.19.0.4:8080/realms/order-realm/protocol/openid-connect/certs

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true